# This builds the dash app into a container and pushes it into the github container registry

name: Build

on:
  
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ] # Publish semver tags as releases.
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io # the github container registry
  IMAGE_NAME: ${{ github.repository }} # github.repository as <account>/<repo> i.e. danny-baker/atlas

jobs:
  
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      # Bake secrets into container
      - name: Injecting secrets
        run: sed -i "s/SECRET_GA4_TAG/$SECRET_GA4_TAG/" ./flask_app/dash_app/dash_html.py     
        env: 
          SECRET_GA4_TAG: ${{ secrets.SECRET_GA4_TAG }}
            
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build the app docker image
        run: docker build . --tag ghcr.io/$IMAGE_NAME/atlas_app
        
      - name: Push app image to github container registry
        run: docker push ghcr.io/$IMAGE_NAME/atlas_app:latest
